version: '2'

services:
  nginx-php-fpm-app:
    image: registry.selfdesign.org/docker/nginx-php-fpm
    container_name: nginx-php-fpm-app
    volumes:
    - ./data/:/www/html
    - ./logs/:/www/logs
    environment:
    - VIRTUAL_HOST=url.hostname.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=url.hostname.com
    - LETSENCRYPT_EMAIL=user@hostname.com

    - ZABBIX_HOSTNAME=nginx-php-fpm-app-app

    - PHP_MEMORY_LIMIT=128M
    - UPLOAD_MAX_SIZE=2G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - PHP_LOG_LEVEL=info
    - PHP_TIMEOUT=300
    - TZ=America/Vancouver
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

